<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> Merge remote-tracking branch 'origin/master'
"""
Django settings for myfirstsite project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

<<<<<<< HEAD
=======
=======
import os
>>>>>>> Merge remote-tracking branch 'origin/master'
>>>>>>> Merge remote-tracking branch 'origin/master'
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = 'django-insecure-5q$f&r5u4oq@q)**l+$0**&q8*)+0jfppu!@r9r-!u&+jggwsz'
=======
<<<<<<< HEAD
SECRET_KEY = 'django-insecure-5q$f&r5u4oq@q)**l+$0**&q8*)+0jfppu!@r9r-!u&+jggwsz'
=======
SECRET_KEY = 'django-insecure-)p9lunw-rs%_n!0aag0az0*@&dwa^r5q)900pe7rj^i+b3v=k%'
>>>>>>> Merge remote-tracking branch 'origin/master'
>>>>>>> Merge remote-tracking branch 'origin/master'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD

=======
<<<<<<< HEAD

=======
>>>>>>> Merge remote-tracking branch 'origin/master'
>>>>>>> Merge remote-tracking branch 'origin/master'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'myfirstsite',
    'catalog',
=======
<<<<<<< HEAD
    'myfirstsite',
    'catalog',
=======
    'catalog'
>>>>>>> Merge remote-tracking branch 'origin/master'
>>>>>>> Merge remote-tracking branch 'origin/master'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myfirstsite.urls'

<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> Merge remote-tracking branch 'origin/master'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
<<<<<<< HEAD
=======
=======
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
>>>>>>> Merge remote-tracking branch 'origin/master'
>>>>>>> Merge remote-tracking branch 'origin/master'
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myfirstsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
